/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:daa51f24-eafd-4b23-b6cd-5b0186930ae2",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_IiG0TPOmh",
    "aws_user_pools_web_client_id": "493ka8jld6kb4i39oo5pahe9p8",
    "oauth": {}
};


export default awsmobile;
